### ISSUE TITLE
ImproperlyConfigured at /sa/

### ISSUE THREAD

**Issue by lucasitz** [chessbr/shuup-project-template#2]
hi ... thanks for ur fast response... but im gettin error yet.. after following the steps, i getting the error when try login:

ImproperlyConfigured at /sa/
Load: Could not import module 'shuup.admin.modules.content.views' to load 'ContentWizardPane' from. (ModuleNotFoundError("No module named 'shuup.admin.modules.content'",))

The terminal server is runing and show the msg:
[2020-01-11 00:41:31,196] (shuup.xtheme.middleware:ERROR): Shop 'Default Shop' has no active theme

**Comment by chessbr** [comment]
Oh boy! I fixed that too! Hopefully now everything works! :smile: 
Also, consider using `shuup-cli` to create a new project, it is easier: https://github.com/chessbr/shuup-cli
